Feature/presentation/product detail UI
f-lab-edu/commerceApp pull request #29
Opened 2024-07-09 17:38 UTC by hyun132

상품 상세화면 기능 구현
- ProductScreen 구현
- 상품 상세 조회, 관련상품 목록 조회 기능 구현

2024-07-09 20:47 UTC, hyun132 commented on app/src/main/java/com/example/commerceapp/ui/product/ProductViewModel.kt
> +                    getRelated(extractedText)
이 부분이 상품 데이터를 불러오고 나서, 이 상품 이름으로 관련된 데이터를 불러오는 함수를 호출하는 부분이에요. 
이 두 요청을 하나의 플로우로 받아서 uistate를 변경하고 싶은데, 두 함수의 순서가 정해져 있을 때 어떻게 구현하면 좋을지 모르겠습니다!
데이터 요청 함수가 성공적으로 데이터를 가져온 경우, 관련 데이터를 불러오는 함수를 연쇄적으로 호출하는 더 좋은 방법이 있을까요?

2024-07-10 01:51 UTC, f-lab-dean requested changes

2024-07-10 01:51 UTC, f-lab-dean commented on app/src/main/java/com/example/commerceapp/ui/product/ProductScreen.kt
> +    val uiState = viewModel.productUiState.collectAsStateWithLifecycle()
by 키워드를 사용하면, `uiState.value`를 `uiState`로 바로 사용할 수 있습니다.

`val uiState by viewModel.productUiState.collectAsStateWithLifecycle()`

2024-07-10 01:51 UTC, f-lab-dean commented on app/src/main/java/com/example/commerceapp/ui/product/ProductScreen.kt
> +
공백을 의도하신게 아니라면, 이런 불필요해 보이는 공백은 지우는게 좋습니다.

2024-07-10 01:51 UTC, f-lab-dean commented on app/src/main/java/com/example/commerceapp/ui/product/ProductScreen.kt
> +    val viewModel: ProductViewModel = hiltViewModel()
viewModel을 컴포저블 함수에 주입하는 것을 권장합니다.

2024-07-10 01:51 UTC, f-lab-dean commented on app/src/main/java/com/example/commerceapp/ui/product/ProductScreen.kt
> +                        containerColor = colorResource(id = R.color.blue_01),
Compose에서는 색상을 관리할 때 꼭 XML 리소스를 활용해야 하는 것은 아닙니다.
Compose의 Color를 상수로 정의하는 것을 고려해보세요.

그리고 머터리얼 테마를 잘 활용하고 있는지, 일관적인 디자인이 적용되고 있는지 고민해보면 좋겠습니다.

2024-07-10 01:51 UTC, f-lab-dean commented on app/src/main/java/com/example/commerceapp/ui/product/ProductScreen.kt
> +                    Text(text = "구매하기")
하드코딩된 텍스트보다 String 리소스를 활용하는 것을 고려해보세요.

2024-07-10 01:51 UTC, f-lab-dean commented on app/src/main/java/com/example/commerceapp/ui/product/ProductScreen.kt
> +                painter = painterResource(id = R.drawable.ic__left_arrow),
여러 이미지 리소스들의 이름에 _ 가 연속으로 두개 있는 것 같아요. 확인해주세요.

2024-07-10 01:51 UTC, f-lab-dean commented on app/src/main/java/com/example/commerceapp/ui/product/ProductScreen.kt
> +            .height(474.dp),
474 dp는 어떤 기준일까요?

2024-07-10 01:51 UTC, f-lab-dean commented on app/src/main/java/com/example/commerceapp/ui/product/ProductViewModel.kt
> +        EMPTY_RESULT,
EMPTY 정도의 이름이어도 충분할 것 같아요.

2024-07-10 01:51 UTC, f-lab-dean commented on app/src/main/java/com/example/commerceapp/ui/product/ProductViewModel.kt
> +                    getRelated(extractedText)
두 함수가 정해져 있고, 항상 함께 순서에 따라 불려야 한다면 저는 다음과 같이 할 듯 합니다.
1. GetProductUseCase 구현
2. GetRelatedProductsUseCase 구현

각 UseCase의 invoke 함수는 suspend 함수이므로, 하나의 코루틴 Job에서 실행이 가능합니다.
```
viewModelScope.launch {
    val product = getProductUseCase.invoke(param)
    val relatedProducts = getRelatedProductsUseCase(param)

   // + UI 상태 처리
   // + Error 처리
}
```

각각의 UseCase 결과에 따라 UI 상태 처리, Error처리가 필요하다면 각각의 단계에 코드를 추가할 수 있습니다.

2024-07-10 20:26 UTC, hyun132 commented on app/src/main/java/com/example/commerceapp/ui/product/ProductScreen.kt
> +    val uiState = viewModel.productUiState.collectAsStateWithLifecycle()
아 그렇네요 수정하겠습니다!

2024-07-10 20:34 UTC, hyun132 commented on app/src/main/java/com/example/commerceapp/ui/product/ProductScreen.kt
> +
넵 유의하겠습니다!

2024-07-11 19:46 UTC, hyun132 commented on app/src/main/java/com/example/commerceapp/ui/product/ProductScreen.kt
> +    val viewModel: ProductViewModel = hiltViewModel()
viewModel을 파라미터로 받도록 수정하라는 말씀이실까요??

2024-07-12 02:41 UTC, f-lab-dean commented on app/src/main/java/com/example/commerceapp/ui/product/ProductScreen.kt
> +    val viewModel: ProductViewModel = hiltViewModel()
넵. Google의 Now in android의 코드를 한번 참고해보세요. :)
- https://github.com/android/nowinandroid/blob/main/feature/foryou/src/main/kotlin/com/google/samples/apps/nowinandroid/feature/foryou/ForYouScreen.kt

주입해주는 것이 UI 테스트, 리컴포지션, ViewModel의 관리 등의 측면에서 유리합니다.

2024-07-13 12:31 UTC, hyun132 commented on app/src/main/java/com/example/commerceapp/ui/product/ProductViewModel.kt
> +        EMPTY_RESULT,
넵 수정하겠습니다!

2024-07-13 14:12 UTC, hyun132 commented on app/src/main/java/com/example/commerceapp/ui/product/ProductViewModel.kt
> +                    getRelated(extractedText)
음 예시로 들어주신 코드에서 getRelatedProductsUseCase의 파라미터가 getProductUseCase를 수행한 결과값을 사용하는 경우라면 어떻게 하면 좋을까요? 
product로 받아온 값이 정상일 때는 getProductUseCase를 호출하고, 아니면 받아온 데이터가 잘못되었음을 ui에 표현해보고 싶은데 어떤식으로 구현해야 할 지 잘 모르겠습니다

2024-07-13 14:14 UTC, hyun132 commented on app/src/main/java/com/example/commerceapp/ui/product/ProductScreen.kt
> +            .height(474.dp),
피그마에 있는 뷰의 사이즈를 그대로 사용했습니다

2024-07-13 14:15 UTC, hyun132 commented on app/src/main/java/com/example/commerceapp/ui/product/ProductScreen.kt
> +                    Text(text = "구매하기")
넵 string리소스로 바꾸겠습니다!

2024-07-13 14:17 UTC, hyun132 commented on app/src/main/java/com/example/commerceapp/ui/product/ProductScreen.kt
> +    val viewModel: ProductViewModel = hiltViewModel()
넵 감사합니다 참고해서 수정하겠습니다!

2024-07-13 15:03 UTC, f-lab-dean commented on app/src/main/java/com/example/commerceapp/ui/product/ProductViewModel.kt
> +                    getRelated(extractedText)
여러가지 방법이 있을 듯 한데요.
한 가지는 getProductUseCase와 getRelatedProductsUseCase를 하나의 UseCase로 만드는 방법이 있을 듯 합니다.
그럼 ProductRepository 에서 Product를 먼저 가져와서 결과를 처리하고, 그 다음 RelatedProduct를 가져와 결과를 처리하게 할 수 있겠죠.

아니면 UseCase는 두 개로 두고 ViewModel에서 각각 UseCase의 결과를 처리하면 될 듯 합니다.

```
viewModelScope.launch {
    val productResult = getProductUseCase.invoke(param)
    if (!productResult.isSuccess) { 
        // error handling
        return
    }

    // 여기에 productResult를 활용해서 파라미터를 만들면 됩니다.
    val relatedProductsResult = getRelatedProductsUseCase(param)
    if (relatedProductsResult.isSuccess) {
        // 에러 핸들링
        return
    }

   // UI 상태 처리
}
```

2024-07-13 17:23 UTC, hyun132 commented on app/src/main/java/com/example/commerceapp/ui/product/ProductScreen.kt
> +                painter = painterResource(id = R.drawable.ic__left_arrow),
넵 변경하겠습니다

2024-07-13 17:49 UTC, f-lab-dean approved these changes
나머지 사항은 다른 PR에서 반영해도 좋습니다.

LGTM!

2024-07-14 11:07 UTC, merged